# app/field_metadata.py

from decimal import Decimal
from datetime import date, time

FIELD_METADATA_MAPPING = {
    # --- General/Header Data (for VesselInfo lookup & MonthlyReportHeader columns) ---
    'vesselname': {'section': 'General', 'field_label': 'Vessel Name', 'target_column': None, 'unit': None, 'type_hint': str},
    'shipname': {'section': 'General', 'field_label': 'Ship Name', 'target_column': None, 'unit': None, 'type_hint': str}, # Alternative field name
    'imo': {'section': 'General', 'field_label': 'IMO No', 'target_column': 'imo_number', 'unit': None, 'type_hint': int},
    'date': {'section': 'General', 'field_label': 'Date', 'target_column': 'report_date', 'unit': None, 'type_hint': date},
    'enginemaker': {'section': 'Control Parameter and config', 'field_label': 'Engine Maker', 'target_column': None, 'unit': None, 'type_hint': str},
    'enginetype': {'section': 'Control Parameter and config', 'field_label': 'Engine Type', 'target_column': None, 'unit': None, 'type_hint': str},
    'model': {'section': 'Control Parameter and config', 'field_label': 'Model', 'target_column': None, 'unit': None, 'type_hint': str},
    'noofcyl': {'section': 'Control Parameter and config', 'field_label': 'No. of Cylinders', 'target_column': None, 'unit': 'cylinders', 'type_hint': int},
    'propellerpitch': {'section': 'Control Parameter and config', 'field_label': 'Propeller Pitch', 'target_column': None, 'unit': 'mm', 'type_hint': Decimal},
    'memcr': {'section': 'Control Parameter and config', 'field_label': 'ME MCR', 'target_column': None, 'unit': 'kW', 'type_hint': Decimal},
    'mcrrpm': {'section': 'Control Parameter and config', 'field_label': 'MCR RPM', 'target_column': None, 'unit': 'RPM', 'type_hint': Decimal},
    'enginerunhrs': {'section': 'General', 'field_label': 'Engine Run Hrs', 'target_column': 'engine_run_hrs', 'unit': 'hours', 'type_hint': Decimal},
    'load': {'section': 'General', 'field_label': 'Load %', 'target_column': 'load_percent', 'unit': '%', 'type_hint': Decimal},
    'rpmpercentage': {'section': 'General', 'field_label': 'RPM %', 'target_column': 'rpm_percent', 'unit': '%', 'type_hint': Decimal},
    'rpm': {'section': 'General', 'field_label': 'RPM', 'target_column': 'rpm', 'unit': 'RPM', 'type_hint': Decimal},
    'shaftpower': {'section': 'General', 'field_label': 'Shaft Power (kW)', 'target_column': 'shaft_power_kw', 'unit': 'kW', 'type_hint': Decimal},
    'loadindicator': {'section': 'General', 'field_label': 'Load Indicator', 'target_column': 'load_indicator', 'unit': None, 'type_hint': Decimal},
    'engineindicatedpowerkw': {'section': 'General', 'field_label': 'Engine Indicated Power (kW)', 'target_column': 'engine_indicated_power_kw', 'unit': 'kW', 'type_hint': Decimal},
    'effectivepower': {'section': 'General', 'field_label': 'Effective Power (kW)', 'target_column': 'effective_power_kw', 'unit': 'kW', 'type_hint': Decimal},
    'eplimplemented': {'section': 'General', 'field_label': 'EPL implemented', 'target_column': 'epl_implemented', 'unit': None, 'type_hint': bool},
    'maxpowerlimitkwafterepl': {'section': 'General', 'field_label': 'Max. power limit (KW)', 'target_column': 'max_power_limit_kw', 'unit': 'kW', 'type_hint': Decimal},
    'maxloadlimitafterepl': {'section': 'General', 'field_label': 'Max load limit (%)after EPL', 'target_column': 'max_load_limit_percent_after_epl', 'unit': '%', 'type_hint': Decimal},

    # --- Core Measured Engine Parameters (Raw values for MonthlyReportHeader) ---
    'pmaxaverage': {'section': 'Performance Parameters', 'field_label': 'Pmax (Average)', 'target_column': 'max_comb_pr_avg_bar', 'unit': 'bar', 'type_hint': Decimal},
    'pcompaverage': {'section': 'Performance Parameters', 'field_label': 'Pcomp (Average)', 'target_column': 'comp_pr_avg_bar', 'unit': 'bar', 'type_hint': Decimal},
    'scavengetemp': {'section': 'General', 'field_label': 'Scavenge Temp (°C)', 'target_column': 'scavenge_temp_c', 'unit': '°C', 'type_hint': Decimal},
    'scavengepr': {'section': 'General', 'field_label': 'Scavenge Pr (Bar)', 'target_column': 'scavenge_pr_bar', 'unit': 'bar', 'type_hint': Decimal},
    'exhaustgastempt/cinlet#1': {'section': 'Turbocharger', 'field_label': 'Exh Gas Temp T/C Inlet', 'target_column': 'tc_exhaust_gas_temp_in_c', 'unit': '°C', 'type_hint': Decimal},
    'exhaustgastempt/coutlet#1': {'section': 'Turbocharger', 'field_label': 'Exh Gas Temp T/C Outlet', 'target_column': 'tc_exhaust_gas_temp_out_c', 'unit': '°C', 'type_hint': Decimal},
    'turbochargerrpm#1': {'section': 'Turbocharger', 'field_label': 'Turbocharger Rpm', 'target_column': 'turbocharger_rpm_avg', 'unit': 'RPM', 'type_hint': Decimal},
    'turbochargerairinlettemp#1': {'section': 'Turbocharger', 'field_label': 'Turbocharger AirInlet Temp (°C)', 'target_column': 'tc_air_inlet_temp_c', 'unit': '°C', 'type_hint': Decimal},
    'pressuredropacrosst/cfilter#1': {'section': 'Turbocharger', 'field_label': 'Pressure Drop Across T/C Filter (mmH2O)', 'target_column': 'tc_filter_dp_mmh2o', 'unit': 'mmH2O', 'type_hint': Decimal},
    'sfoc': {'section': 'Fuel Oil System', 'field_label': 'SFOC (g/kWH)', 'target_column': 'sfoc_measured_g_kwh', 'unit': 'g/kWH', 'type_hint': Decimal},
    'sfoccalculated': {'section': 'Fuel Oil System', 'field_label': 'SFOC Calculated (g/kWH)', 'target_column': 'sfoc_calculated_g_kwh', 'unit': 'g/kWH', 'type_hint': Decimal},
    'foconsumptionmt_hr': {'section': 'Fuel Oil System', 'field_label': 'FO Consumption MT/hr', 'target_column': 'fo_consumption_mt_hr', 'unit': 'MT/hr', 'type_hint': Decimal},
    'pumpmark/fuelindexaverage': {'section': 'Performance Parameters', 'field_label': 'Fuel Injection Pump Index (mm)', 'target_column': 'fuel_injection_pump_index_mm', 'unit': None, 'type_hint': Decimal},
    'fuel_inj_pump_index_mm': {'section': 'Performance Parameters', 'field_label': 'Fuel Injection Pump Index (mm)', 'target_column': 'fuel_injection_pump_index_mm', 'unit': None, 'type_hint': Decimal},
    'exhausttempaverage': {'section': 'Performance Parameters', 'field_label': 'Exhaust Temp °C', 'target_column': 'exh_temp_cylinder_outlet_ave_c', 'unit': '°C', 'type_hint': Decimal},

    # --- Environmental and Operational ---
    'barometricpressure': {'section': 'General', 'field_label': 'Barometric Pressure (mbar)', 'target_column': 'barometric_pressure_mmh2o', 'unit': 'mbar', 'type_hint': Decimal},
    'seawatertemp': {'section': 'General', 'field_label': 'Sea Water Temp (°C)', 'target_column': 'sea_water_temp_c', 'unit': '°C', 'type_hint': Decimal},
    'engineroomtemp': {'section': 'General', 'field_label': 'Engine Room Temp (°C)', 'target_column': 'engine_room_temp_c', 'unit': '°C', 'type_hint': Decimal},
    'egbpressuredrop': {'section': 'General', 'field_label': 'EGB Pressure Drop (mmH2O)', 'target_column': 'egb_pressure_drop_mmh2o', 'unit': 'mmH2O', 'type_hint': Decimal},
    'shipcondition': {'section': 'General', 'field_label': 'Ship Condition', 'target_column': 'ship_condition', 'unit': None, 'type_hint': str},
    'displacement': {'section': 'General', 'field_label': 'Displacement (MT)', 'target_column': 'displacement_mt', 'unit': 'MT', 'type_hint': Decimal},
    'draftf': {'section': 'General', 'field_label': 'Draft(F)', 'target_column': 'draft_f', 'unit': 'm', 'type_hint': Decimal},
    'drafta': {'section': 'General', 'field_label': 'Draft(A)', 'target_column': 'draft_a', 'unit': 'm', 'type_hint': Decimal},
    'trim': {'section': 'General', 'field_label': 'Trim (mtr)', 'target_column': 'trim_mtr', 'unit': 'mtr', 'type_hint': Decimal},
    'windforce': {'section': 'General', 'field_label': 'Wind Force', 'target_column': 'wind_force', 'unit': None, 'type_hint': str},
    'Seastate': {'section': 'General', 'field_label': 'Sea State', 'target_column': 'sea_state', 'unit': None, 'type_hint': str},
    'weather': {'section': 'General', 'field_label': 'Weather', 'target_column': 'weather', 'unit': None, 'type_hint': str},
    'location': {'section': 'General', 'field_label': 'Location', 'target_column': 'location', 'unit': None, 'type_hint': str},
    'speedgpskn': {'section': 'General', 'field_label': 'Speed (GPS) Kn', 'target_column': 'speed_gps_kn', 'unit': 'knots', 'type_hint': Decimal},
    'speedlogkn': {'section': 'General', 'field_label': 'Speed (Log) Kn', 'target_column': 'speed_log_kn', 'unit': 'knots', 'type_hint': Decimal},
    'speedbypitchkn': {'section': 'General', 'field_label': 'Speed (By Pitch) Kn', 'target_column': 'speed_by_pitch_kn', 'unit': 'knots', 'type_hint': Decimal},
    'slip%': {'section': 'General', 'field_label': 'Slip %', 'target_column': 'slip_percent', 'unit': '%', 'type_hint': Decimal},
    'timestart': {'section': 'Time & Counters', 'field_label': 'Time Start', 'target_column': 'time_start', 'unit': 'HH:MM', 'type_hint': time},
    'timefinish': {'section': 'Time & Counters', 'field_label': 'Time Finish', 'target_column': 'time_finish', 'unit': 'HH:MM', 'type_hint': time},
    'revolutioncounterstart': {'section': 'Time & Counters', 'field_label': 'Revolution Counter Start', 'target_column': 'revolution_counter_start', 'unit': 'revolutions', 'type_hint': Decimal},
    'revolutioncounterfinish': {'section': 'Time & Counters', 'field_label': 'Revolution Counter Finish', 'target_column': 'revolution_counter_finish', 'unit': 'revolutions', 'type_hint': Decimal},
    'measuredby': {'section': 'Remarks', 'field_label': 'Measured By', 'target_column': 'measured_by', 'unit': None, 'type_hint': str},
    'chiefengineersign': {'section': 'Remarks', 'field_label': 'Chief Engineer Name / Sign', 'target_column': 'chief_engineer_name', 'unit': None, 'type_hint': str},
    'formname': {'section': 'Remarks', 'field_label': 'Tech Farm No', 'target_column': 'tech_form_no', 'unit': None, 'type_hint': str},
    'editionno': {'section': 'Remarks', 'field_label': 'Edition No', 'target_column': 'edition_no', 'unit': None, 'type_hint': int},
    'revno': {'section': 'Remarks', 'field_label': 'Revision No', 'target_column': 'revision_no', 'unit': None, 'type_hint': int},
    'revdate': {'section': 'Remarks', 'field_label': 'Revision Date', 'target_column': 'revision_date', 'unit': None, 'type_hint': date},
    
    # --- Other fields to store in JSONB details only ---
    'reportmonth': {'section': 'General', 'field_label': 'Report Month Label', 'target_column': None, 'unit': None, 'type_hint': str},
    'maxpmaxdeviation': {'section': 'Control Parameter and config', 'field_label': 'Max Pmax Deviation', 'target_column': None, 'unit': '%', 'type_hint': Decimal},
    'maxpcompdeviation': {'section': 'Control Parameter and config', 'field_label': 'Max Pcom Deviation', 'target_column': None, 'unit': '%', 'type_hint': Decimal},
    'unitexhtempdeviation': {'section': 'Control Parameter and config', 'field_label': 'Unit Exh Temp Deviation', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'mincyloilfeedratesetting': {'section': 'Control Parameter and config', 'field_label': 'Min Cyl.Oil Feed Rate Setting', 'target_column': None, 'unit': 'kg/MWh', 'type_hint': Decimal},
    'fuelpumpmarkdeviation': {'section': 'Control Parameter and config', 'field_label': 'Fuel Pump Mark Deviation', 'target_column': None, 'unit': '%', 'type_hint': Decimal},
    'maxcyloilfeedratesetting': {'section': 'Control Parameter and config', 'field_label': 'Max Cyl.Oil Feed Rate Setting', 'target_column': None, 'unit': 'kg/MWh', 'type_hint': Decimal},
    'vitindexdeviation': {'section': 'Control Parameter and config', 'field_label': 'VIT Index Deviation', 'target_column': None, 'unit': '%', 'type_hint': Decimal},
    'maxmeaneffectiveprdeviation': {'section': 'Control Parameter and config', 'field_label': 'Max Mean Effective Pr Deviation', 'target_column': None, 'unit': '%', 'type_hint': Decimal},
    'minjcwtempinlet': {'section': 'Control Parameter and config', 'field_label': 'Min JCW Temp Inlet', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'maxjcwtempoutlet': {'section': 'Control Parameter and config', 'field_label': 'Max JCW Temp Outlet', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'fograde': {'section': 'Fuel Oil System', 'field_label': 'FO Grade', 'target_column': None, 'unit': None, 'type_hint': str},
    'density@15c': {'section': 'Fuel Oil System', 'field_label': 'Density @15 °C (Kg/M3)', 'target_column': None, 'unit': 'kg/m³', 'type_hint': Decimal},
    'totalmassasperbdn/fosulphur%': {'section': 'Fuel Oil System', 'field_label': 'FO Sulphur (%)', 'target_column': None, 'unit': '%', 'type_hint': Decimal},
    'netenergyasperbdn/folcv': {'section': 'Fuel Oil System', 'field_label': 'FO LCV (MJ/Kg)', 'target_column': None, 'unit': 'MJ/kg', 'type_hint': Decimal},
    'viscocity@50c': {'section': 'Fuel Oil System', 'field_label': 'Viscosity @50 °C', 'target_column': None, 'unit': 'cSt', 'type_hint': Decimal},
    'fopressurebar': {'section': 'Fuel Oil System', 'field_label': 'FO Pressure (Bar)', 'target_column': None, 'unit': 'bar', 'type_hint': Decimal},
    'fotempatengine': {'section': 'Fuel Oil System', 'field_label': 'FO Temp at Engine (°C)', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'fotempatflowmeter': {'section': 'Fuel Oil System', 'field_label': 'FO Temp at Flowmeter (°C)', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'correcteddensityfo': {'section': 'Fuel Oil System', 'field_label': 'Corrected Density FO (Kg/m3)', 'target_column': None, 'unit': 'kg/m³', 'type_hint': Decimal},
    'foconsumptionmt_hr_kg_h': {'section': 'Fuel Oil System', 'field_label': 'FO Consumption kg/h', 'target_column': None, 'unit': 'kg/h', 'type_hint': Decimal},
    'lopressureeng': {'section': 'Lub Oil System', 'field_label': 'LO Pressure Eng (Bar)', 'target_column': None, 'unit': 'bar', 'type_hint': Decimal},
    'cyllotbn': {'section': 'Lub Oil System', 'field_label': 'CYL LO TBN', 'target_column': None, 'unit': 'TBN', 'type_hint': str},
    'cyloilconsumptionltrs/day': {'section': 'Lub Oil System', 'field_label': 'CYL Oil Consumption (Ltrs/Day)', 'target_column': None, 'unit': 'liters/day', 'type_hint': Decimal},
    'cyllodensity@15c': {'section': 'Lub Oil System', 'field_label': 'CYL.LO Density @15 °C (Kg/m3)', 'target_column': None, 'unit': 'kg/m³', 'type_hint': Decimal},
    'cyloilfeedratesetting': {'section': 'Lub Oil System', 'field_label': 'Cyl Oil Feed Rate (Setting)', 'target_column': None, 'unit': 'kg/MWh', 'type_hint': Decimal},
    'scylocactualg/kwh': {'section': 'Lub Oil System', 'field_label': 'SCYLOC (Actual) (g/kWHr)', 'target_column': None, 'unit': 'g/kWh', 'type_hint': Decimal},
    'lo temperatureengineinlet': {'section': 'Lub Oil System', 'field_label': 'LO Temperature Engine Inlet (°C)', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'thrustbearinglotemp': {'section': 'Lub Oil System', 'field_label': 'Thrust Bearing LO Temp (°C)', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'lopresst/cinlet#1': {'section': 'Turbocharger', 'field_label': 'LO Press T/C Inlet (Bar)', 'target_column': None, 'unit': 'bar', 'type_hint': Decimal},
    'lotempt/cinlet#1': {'section': 'Turbocharger', 'field_label': 'LO Temp T/C Inlet (°C)', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'lotempt/coutlet#1': {'section': 'Turbocharger', 'field_label': 'LO Temp T/C Outlet (°C)', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'cwtempaircoolerinlet#1': {'section': 'Air Cooler', 'field_label': 'CW Temp Air Cooler Inlet (°C)', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'cwtempaircooleroutlet#1': {'section': 'Air Cooler', 'field_label': 'CW Temp Air Cooler Outlet (°C)', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'pressdropacrossaircooler#1': {'section': 'Air Cooler', 'field_label': 'Pressure Drop Across Air Cooler (mmWG)', 'target_column': None, 'unit': 'mmWG', 'type_hint': Decimal},
    'tempaircoolerinlet#1': {'section': 'Air Cooler', 'field_label': 'Air Temp Air Cooler Inlet (°C)', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'tempaircooleroutlet#1': {'section': 'Air Cooler', 'field_label': 'Air Temp Air Cooler Outlet (°C)', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'meaneffectivepraverage': {'section': 'Performance Parameters', 'field_label': 'Mean Effective Presure (Pe) (bar)', 'target_column': None, 'unit': 'bar', 'type_hint': Decimal},
    'indicatedpoweraverage': {'section': 'Performance Parameters', 'field_label': 'Indicated Power (kW)', 'target_column': None, 'unit': 'kW', 'type_hint': Decimal},
    'vitindexaverage': {'section': 'Performance Parameters', 'field_label': 'VIT Index', 'target_column': None, 'unit': None, 'type_hint': Decimal},
    'jcwtempinletaverage': {'section': 'Performance Parameters', 'field_label': 'JCW Temp-Inlet °C', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'jcwtempoutletaverage': {'section': 'Performance Parameters', 'field_label': 'JCW Temp-Outlet °C', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    'pcotempoutletaverage': {'section': 'Performance Parameters', 'field_label': 'PCO Temp -Outlet °C', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},

    # Other misc fields
    'techno': {'section': 'General', 'field_label': 'Tech No', 'target_column': None, 'unit': None, 'type_hint': str},
    'Text7': {'section': 'General', 'field_label': 'Text7', 'target_column': None, 'unit': None, 'type_hint': str},
    'model_dup': {'section': 'General', 'field_label': 'Model Dup', 'target_column': None, 'unit': None, 'type_hint': str},
    'enginemaker_dup': {'section': 'General', 'field_label': 'Engine Maker Dup', 'target_column': None, 'unit': None, 'type_hint': str},
    'maxpowerlimitkwaftereplselection': {'section': 'General', 'field_label': 'Max Power Limit Selection', 'target_column': None, 'unit': None, 'type_hint': str},
    'maxloadlimitpercentageafereplselection': {'section': 'General', 'field_label': 'Max Load Limit Selection', 'target_column': None, 'unit': None, 'type_hint': str},
    'netenergyasperbdn/folcvselection': {'section': 'Fuel Oil System', 'field_label': 'FO LCV Selection', 'target_column': None, 'unit': None, 'type_hint': str},
    'totalmassasperbdn/fosulphurpercentageselection': {'section': 'Fuel Oil System', 'field_label': 'FO Sulphur Selection', 'target_column': None, 'unit': None, 'type_hint': str},
}

# Add entries for cylinders #2 through #6 dynamically (these will remain in JSONB details)
for i in range(1, 7):
    FIELD_METADATA_MAPPING.update({
        f"pmax#{i}": {'section': 'Performance Parameters', 'field_label': f'Pmax (#{i})', 'target_column': None, 'unit': 'bar', 'type_hint': Decimal},
        f"pcomp#{i}": {'section': 'Performance Parameters', 'field_label': f'Pcomp (#{i})', 'target_column': None, 'unit': 'bar', 'type_hint': Decimal},
        f"meaneffectivepr#{i}": {'section': 'Performance Parameters', 'field_label': f'Mean Effective Pr (#{i})', 'target_column': None, 'unit': 'bar', 'type_hint': Decimal},
        f"indicatedpower#{i}": {'section': 'Performance Parameters', 'field_label': f'Indicated Power (#{i})', 'target_column': None, 'unit': 'kW', 'type_hint': Decimal},
        f"exhausttemp#{i}": {'section': 'Performance Parameters', 'field_label': f'Exhaust Temp (#{i})', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
        f"pumpmark/fuelindex#{i}": {'section': 'Performance Parameters', 'field_label': f'Pump Mark / Fuel Index (#{i})', 'target_column': None, 'unit': None, 'type_hint': Decimal},
        f"vitindex#{i}": {'section': 'Performance Parameters', 'field_label': f'VIT Index (#{i})', 'target_column': None, 'unit': None, 'type_hint': Decimal},
        f"jcwtempinlet#{i}": {'section': 'Performance Parameters', 'field_label': f'JCW Temp-Inlet (#{i})', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
        f"jcwtempoutlet#{i}": {'section': 'Performance Parameters', 'field_label': f'JCW Temp-Outlet (#{i})', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
        f"pcotempoutlet#{i}": {'section': 'Performance Parameters', 'field_label': f'PCO Temp -Outlet (#{i})', 'target_column': None, 'unit': '°C', 'type_hint': Decimal},
    })