"""Initial schema baseline

Revision ID: e22287619ca9
Revises: 
Create Date: 2026-09-29 10:31:56.123732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e22287619ca9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_column('report_configs', 'last_triggered_date')
    op.drop_column('report_configs', 'last_triggered_at')
    op.create_index(op.f('ix_report_notifications_thread_id'), 'report_notifications', ['thread_id'], unique=False)
    op.alter_column('report_thread_attachments', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_thread_attachments', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_report_notifications_thread_id'), table_name='report_notifications')
    op.add_column('report_configs', sa.Column('last_triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('report_configs', sa.Column('last_triggered_date', sa.DATE(), autoincrement=False, nullable=True))
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
