"""Add AE alert tables

Revision ID: 193ddde9b102
Revises: d06c6eeb99da
Create Date: 2025-11-06 17:07:29.280883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '193ddde9b102'
down_revision: Union[str, Sequence[str], None] = 'd06c6eeb99da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ae_alert_summary',
    sa.Column('summary_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('generator_id', sa.Integer(), nullable=False),
    sa.Column('vessel_name', sa.String(length=100), nullable=False, comment='Denormalized for fast queries'),
    sa.Column('generator_designation', sa.String(length=50), nullable=False, comment="e.g., 'Aux Engine No.1'"),
    sa.Column('imo_number', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.DATE(), nullable=False),
    sa.Column('report_month', sa.String(length=20), nullable=False),
    sa.Column('normal_count', sa.Integer(), nullable=False, comment='Number of normal-status metrics'),
    sa.Column('warning_count', sa.Integer(), nullable=False, comment='Number of warning-level alerts'),
    sa.Column('critical_count', sa.Integer(), nullable=False, comment='Number of critical-level alerts'),
    sa.Column('dominant_status', sa.String(length=20), nullable=False, comment="Overall status: 'Normal', 'Warning', or 'Critical'"),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['generator_id'], ['vessel_generator.generator_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['generator_monthly_report_header.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index(op.f('ix_ae_alert_summary_generator_id'), 'ae_alert_summary', ['generator_id'], unique=False)
    op.create_index(op.f('ix_ae_alert_summary_imo_number'), 'ae_alert_summary', ['imo_number'], unique=False)
    op.create_index(op.f('ix_ae_alert_summary_report_date'), 'ae_alert_summary', ['report_date'], unique=False)
    op.create_index(op.f('ix_ae_alert_summary_report_id'), 'ae_alert_summary', ['report_id'], unique=True)
    op.create_index(op.f('ix_ae_alert_summary_report_month'), 'ae_alert_summary', ['report_month'], unique=False)
    op.create_table('ae_critical_alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('generator_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('baseline_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('actual_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deviation', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deviation_pct', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['generator_id'], ['vessel_generator.generator_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['generator_monthly_report_header.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ae_critical_alert_generator_id'), 'ae_critical_alert', ['generator_id'], unique=False)
    op.create_index(op.f('ix_ae_critical_alert_report_id'), 'ae_critical_alert', ['report_id'], unique=False)
    op.create_table('ae_normal_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('generator_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False, comment="Display name of the metric (e.g., 'Pmax (Bar)')"),
    sa.Column('baseline_value', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Shop trial baseline value'),
    sa.Column('actual_value', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Measured actual value'),
    sa.Column('deviation', sa.DECIMAL(precision=10, scale=2), nullable=True, comment='Absolute deviation (actual - baseline)'),
    sa.Column('deviation_pct', sa.DECIMAL(precision=6, scale=2), nullable=True, comment='Percentage deviation'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['generator_id'], ['vessel_generator.generator_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['generator_monthly_report_header.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ae_normal_status_generator_id'), 'ae_normal_status', ['generator_id'], unique=False)
    op.create_index(op.f('ix_ae_normal_status_report_id'), 'ae_normal_status', ['report_id'], unique=False)
    op.create_table('ae_warning_alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('generator_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('baseline_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('actual_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deviation', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('deviation_pct', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['generator_id'], ['vessel_generator.generator_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['generator_monthly_report_header.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ae_warning_alert_generator_id'), 'ae_warning_alert', ['generator_id'], unique=False)
    op.create_index(op.f('ix_ae_warning_alert_report_id'), 'ae_warning_alert', ['report_id'], unique=False)
    op.drop_index(op.f('ix_me_normal_status_wide_status_id'), table_name='me_normal_status_wide')
    op.drop_table('me_normal_status_wide')
    op.drop_index(op.f('ix_me_warning_alerts_wide_alert_id'), table_name='me_warning_alerts_wide')
    op.drop_table('me_warning_alerts_wide')
    op.alter_column('me_critical_alert', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_me_critical_report_id'), table_name='me_critical_alert')
    op.create_index(op.f('ix_me_critical_alert_report_id'), 'me_critical_alert', ['report_id'], unique=False)
    op.alter_column('me_normal_status', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_me_normal_report_id'), table_name='me_normal_status')
    op.create_index(op.f('ix_me_normal_status_report_id'), 'me_normal_status', ['report_id'], unique=False)
    op.alter_column('me_warning_alert', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('idx_me_warning_report_id'), table_name='me_warning_alert')
    op.create_index(op.f('ix_me_warning_alert_report_id'), 'me_warning_alert', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_me_warning_alert_report_id'), table_name='me_warning_alert')
    op.create_index(op.f('idx_me_warning_report_id'), 'me_warning_alert', ['report_id'], unique=False)
    op.alter_column('me_warning_alert', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.drop_index(op.f('ix_me_normal_status_report_id'), table_name='me_normal_status')
    op.create_index(op.f('idx_me_normal_report_id'), 'me_normal_status', ['report_id'], unique=False)
    op.alter_column('me_normal_status', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.drop_index(op.f('ix_me_critical_alert_report_id'), table_name='me_critical_alert')
    op.create_index(op.f('idx_me_critical_report_id'), 'me_critical_alert', ['report_id'], unique=False)
    op.alter_column('me_critical_alert', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.create_table('me_warning_alerts_wide',
    sa.Column('alert_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sfoc_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='SFOC Actual Value'),
    sa.Column('sfoc_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='SFOC Baseline Value'),
    sa.Column('sfoc_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='SFOC Actual - Baseline'),
    sa.Column('sfoc_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='SFOC Deviation %'),
    sa.Column('pmax_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Pmax Actual Value'),
    sa.Column('pmax_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Pmax Baseline Value'),
    sa.Column('pmax_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Pmax Actual - Baseline'),
    sa.Column('pmax_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Pmax Deviation %'),
    sa.Column('turbospeed_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Turbospeed Actual Value'),
    sa.Column('turbospeed_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Turbospeed Baseline Value'),
    sa.Column('turbospeed_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Turbospeed Actual - Baseline'),
    sa.Column('turbospeed_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Turbospeed Deviation %'),
    sa.Column('engspeed_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='EngSpeed Actual Value'),
    sa.Column('engspeed_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='EngSpeed Baseline Value'),
    sa.Column('engspeed_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='EngSpeed Actual - Baseline'),
    sa.Column('engspeed_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='EngSpeed Deviation %'),
    sa.Column('scavair_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='ScavAir Actual Value'),
    sa.Column('scavair_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='ScavAir Baseline Value'),
    sa.Column('scavair_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='ScavAir Actual - Baseline'),
    sa.Column('scavair_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='ScavAir Deviation %'),
    sa.Column('exh_t_c_inlet_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_inlet Actual Value'),
    sa.Column('exh_t_c_inlet_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_inlet Baseline Value'),
    sa.Column('exh_t_c_inlet_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_inlet Actual - Baseline'),
    sa.Column('exh_t_c_inlet_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_inlet Deviation %'),
    sa.Column('exh_cylinder_outlet_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_Cylinder_outlet Actual Value'),
    sa.Column('exh_cylinder_outlet_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_Cylinder_outlet Baseline Value'),
    sa.Column('exh_cylinder_outlet_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_Cylinder_outlet Actual - Baseline'),
    sa.Column('exh_cylinder_outlet_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_Cylinder_outlet Deviation %'),
    sa.Column('exh_t_c_outlet_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_outlet Actual Value'),
    sa.Column('exh_t_c_outlet_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_outlet Baseline Value'),
    sa.Column('exh_t_c_outlet_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_outlet Actual - Baseline'),
    sa.Column('exh_t_c_outlet_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_outlet Deviation %'),
    sa.Column('fipi_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FIPI Actual Value'),
    sa.Column('fipi_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FIPI Baseline Value'),
    sa.Column('fipi_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FIPI Actual - Baseline'),
    sa.Column('fipi_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FIPI Deviation %'),
    sa.Column('foc_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FOC Actual Value'),
    sa.Column('foc_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FOC Baseline Value'),
    sa.Column('foc_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FOC Actual - Baseline'),
    sa.Column('foc_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FOC Deviation %'),
    sa.ForeignKeyConstraint(['report_id'], ['monthly_report_header.report_id'], name=op.f('me_warning_alerts_wide_report_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', name=op.f('me_warning_alerts_wide_pkey')),
    sa.UniqueConstraint('report_id', name=op.f('me_warning_alerts_wide_report_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_me_warning_alerts_wide_alert_id'), 'me_warning_alerts_wide', ['alert_id'], unique=False)
    op.create_table('me_normal_status_wide',
    sa.Column('status_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sfoc_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='SFOC Actual Value'),
    sa.Column('sfoc_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='SFOC Baseline Value'),
    sa.Column('sfoc_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='SFOC Actual - Baseline'),
    sa.Column('sfoc_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='SFOC Deviation %'),
    sa.Column('pmax_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Pmax Actual Value'),
    sa.Column('pmax_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Pmax Baseline Value'),
    sa.Column('pmax_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Pmax Actual - Baseline'),
    sa.Column('pmax_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Pmax Deviation %'),
    sa.Column('turbospeed_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Turbospeed Actual Value'),
    sa.Column('turbospeed_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Turbospeed Baseline Value'),
    sa.Column('turbospeed_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Turbospeed Actual - Baseline'),
    sa.Column('turbospeed_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Turbospeed Deviation %'),
    sa.Column('engspeed_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='EngSpeed Actual Value'),
    sa.Column('engspeed_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='EngSpeed Baseline Value'),
    sa.Column('engspeed_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='EngSpeed Actual - Baseline'),
    sa.Column('engspeed_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='EngSpeed Deviation %'),
    sa.Column('scavair_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='ScavAir Actual Value'),
    sa.Column('scavair_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='ScavAir Baseline Value'),
    sa.Column('scavair_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='ScavAir Actual - Baseline'),
    sa.Column('scavair_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='ScavAir Deviation %'),
    sa.Column('exh_t_c_inlet_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_inlet Actual Value'),
    sa.Column('exh_t_c_inlet_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_inlet Baseline Value'),
    sa.Column('exh_t_c_inlet_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_inlet Actual - Baseline'),
    sa.Column('exh_t_c_inlet_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_inlet Deviation %'),
    sa.Column('exh_cylinder_outlet_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_Cylinder_outlet Actual Value'),
    sa.Column('exh_cylinder_outlet_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_Cylinder_outlet Baseline Value'),
    sa.Column('exh_cylinder_outlet_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_Cylinder_outlet Actual - Baseline'),
    sa.Column('exh_cylinder_outlet_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_Cylinder_outlet Deviation %'),
    sa.Column('exh_t_c_outlet_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_outlet Actual Value'),
    sa.Column('exh_t_c_outlet_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_outlet Baseline Value'),
    sa.Column('exh_t_c_outlet_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_outlet Actual - Baseline'),
    sa.Column('exh_t_c_outlet_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exh_T_C_outlet Deviation %'),
    sa.Column('fipi_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FIPI Actual Value'),
    sa.Column('fipi_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FIPI Baseline Value'),
    sa.Column('fipi_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FIPI Actual - Baseline'),
    sa.Column('fipi_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FIPI Deviation %'),
    sa.Column('foc_actual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FOC Actual Value'),
    sa.Column('foc_baseline', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FOC Baseline Value'),
    sa.Column('foc_deviation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FOC Actual - Baseline'),
    sa.Column('foc_deviation_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='FOC Deviation %'),
    sa.ForeignKeyConstraint(['report_id'], ['monthly_report_header.report_id'], name=op.f('me_normal_status_wide_report_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('status_id', name=op.f('me_normal_status_wide_pkey')),
    sa.UniqueConstraint('report_id', name=op.f('me_normal_status_wide_report_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_me_normal_status_wide_status_id'), 'me_normal_status_wide', ['status_id'], unique=False)
    op.drop_index(op.f('ix_ae_warning_alert_report_id'), table_name='ae_warning_alert')
    op.drop_index(op.f('ix_ae_warning_alert_generator_id'), table_name='ae_warning_alert')
    op.drop_table('ae_warning_alert')
    op.drop_index(op.f('ix_ae_normal_status_report_id'), table_name='ae_normal_status')
    op.drop_index(op.f('ix_ae_normal_status_generator_id'), table_name='ae_normal_status')
    op.drop_table('ae_normal_status')
    op.drop_index(op.f('ix_ae_critical_alert_report_id'), table_name='ae_critical_alert')
    op.drop_index(op.f('ix_ae_critical_alert_generator_id'), table_name='ae_critical_alert')
    op.drop_table('ae_critical_alert')
    op.drop_index(op.f('ix_ae_alert_summary_report_month'), table_name='ae_alert_summary')
    op.drop_index(op.f('ix_ae_alert_summary_report_id'), table_name='ae_alert_summary')
    op.drop_index(op.f('ix_ae_alert_summary_report_date'), table_name='ae_alert_summary')
    op.drop_index(op.f('ix_ae_alert_summary_imo_number'), table_name='ae_alert_summary')
    op.drop_index(op.f('ix_ae_alert_summary_generator_id'), table_name='ae_alert_summary')
    op.drop_table('ae_alert_summary')
    # ### end Alembic commands ###
