"""Initial schema

Revision ID: 898cbeae3141
Revises: 
Create Date: 2026-01-18 15:36:07.818797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '898cbeae3141'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vessels',
    sa.Column('imo', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vessel_type', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('imo')
    )
    op.create_index(op.f('ix_vessels_imo'), 'vessels', ['imo'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vessel_imo', sa.String(length=7), nullable=False),
    sa.Column('reported_by_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('equipment_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ships_remarks', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('NORMAL', 'HIGH', 'MEDIUM', 'CRITICAL', name='defectpriority'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED', name='defectstatus'), nullable=True),
    sa.Column('office_support_required', sa.Boolean(), nullable=True),
    sa.Column('pr_number', sa.String(), nullable=True),
    sa.Column('pr_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('responsibility', sa.String(), nullable=True),
    sa.Column('json_backup_path', sa.String(), nullable=True),
    sa.Column('date_identified', sa.DateTime(), nullable=True),
    sa.Column('target_close_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vessel_imo'], ['vessels.imo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_is_deleted'), 'defects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_defects_priority'), 'defects', ['priority'], unique=False)
    op.create_index(op.f('ix_defects_status'), 'defects', ['status'], unique=False)
    op.create_index(op.f('ix_defects_vessel_imo'), 'defects', ['vessel_imo'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('MENTION', 'ALERT', 'SYSTEM', name='notificationtype'), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('user_vessel_link',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vessel_imo', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vessel_imo'], ['vessels.imo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'vessel_imo')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='taskstatus'), nullable=True),
    sa.Column('defect_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_id'), 'tasks', ['assigned_to_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('defect_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('author_role', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tagged_user_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('blob_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('threads')
    op.drop_index(op.f('ix_tasks_assigned_to_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('user_vessel_link')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_defects_vessel_imo'), table_name='defects')
    op.drop_index(op.f('ix_defects_status'), table_name='defects')
    op.drop_index(op.f('ix_defects_priority'), table_name='defects')
    op.drop_index(op.f('ix_defects_is_deleted'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_vessels_imo'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
